<h1>Learning Python via ML  :D </h1><b> Creation of numpy array</b>

In [15]:
# Getting started with numpy
import numpy as np



arr1 = np.ones((2,2))
print "Ones Arrray:\n" ,arr1

arr2 = np.zeros((2,2))
print "Zeros array:\n" , arr2

arr3 = np.array([1,2,3,4])
print "data array:\n",arr3

arr4 = np.full((2,2),7.0)
print "constant full array:\n",arr4

arr5 = np.eye(2)
print "Identity Matrix:\n",arr5

arr6= np.random.random((2,2))
print "Random array:\n",arr6



Ones Arrray:
[[ 1.  1.]
 [ 1.  1.]]
Zeros array:
[[ 0.  0.]
 [ 0.  0.]]
data array:
[1 2 3 4]
constant full array:
[[ 7.  7.]
 [ 7.  7.]]
Identity Matrix:
[[ 1.  0.]
 [ 0.  1.]]
Random array:
[[ 0.74583515  0.09280694]
 [ 0.18666792  0.30002827]]


<b>2. Slicing and dicing </b>

In [20]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.dtype


dtype('int64')

In [36]:
#Basic Linear regression class
%matplotlib inline
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from IPython.core.pylabtools import figsize


"""
This is a simple linear regression class. The idea is to familiarize the constructs of python, 
numpy and how to write efficient ml codes in python.

"""

class LinearRegression(object):
    weight = None
    learningRate = 0.00001
    def __init__(self,inputSize,learningRate=0.00001):
        self.weight = np.zeros(inputSize+1)
        self.learningRate = learningRate
        
    def predict(self,testInp):
        finalOut = np.zeros(testInp.shape[0])
        for idx in range(testInp.shape[0]): 
            finalOut[idx] = np.dot(np.append(testInp[idx],1.0) ,self.weight.transpose())
        return finalOut

    """
        trainX - should be a m x n matrix  
        label -  should be n x 1 vector that contains the corresponding label of each training set
        gd - represents the type of gradient descent to use 2 options now: 
            [i]  BGD - Batch Gradient Descent
            [ii] SGD - Stochastic Gradient Descent (default)
    """
    def train(self,trainX,label,numEpochs=100000):
        print "Training started"
        for i in range(numEpochs):
            for idx in range(trainX.shape[0]):
                trainingRow = np.append(trainX[idx],1.0)
                thetaX = np.dot(trainingRow ,self.weight.transpose())
                delta =  trainingRow * (thetaX - label[idx])
                self.weight = self.weight - (self.learningRate * delta)
        print "Training Ended"       
                
    def printWeights(self):
        print "Weights:",self.weight
                
    def plot(self,trainX,label):
        figsize(40,50)
        plt.xlabel("Index")
        plt.ylabel("Predicted Output")
        plt.xlim(5)
        pred = self.predict(trainX)
        xCoords = [i+1 for i in range(trainX.shape[0]+1)]
        plt.plot(xCoords,pred,color='r')
        plt.plot(xCoords,label,color='b')
        #plt.show()

# Let's test

randInp = np.random.randint(2,30,size=(4,3))
print randInp
def fx(inp):
    return np.dot(inp , np.array([3,5,9]).transpose())
labelOut = fx(randInp)
print labelOut
#print "Random Input\n", randInp

print "Corr Label:\n",labelOut

#print "Let's start Training .."

reg = LinearRegression(3)
reg.train(randInp,labelOut)

print "Predicted:\n",reg.predict(randInp)

print reg.printWeights()

[[13 10  9]
 [19 26  5]
 [ 2 13  2]
 [23  5 13]]
[170 232  89 211]
Corr Label:
[170 232  89 211]
Training started
Training Ended
Predicted:
[ 169.79786345  231.968206     89.16800761  211.12419249]
Weights: [ 3.08079071  4.9276382   8.78915322  1.36882316]
None


In [37]:
# Logistic Regression implementation
import numpy as np
import matplotlib.pyplot as plt
from math import exp
class LogisticRegression(object):
    weight  = None
    def __init__(self,numInput,learningRate=0.0001):
        self.weight = np.zeros(numInput+1)
        self.learningRate = learningRate
    
    def sigmoid(inp):
        return 1/1+exp(-inp)
    
    def predict(self,testInp):
        finalOut = np.zeros(testInp.shape[0])
        for idx in range(testInp.shape[0]):
            finalOut[idx] = np.dot(np.append(testInp[idx],1.0),self.weight.transpose())
        return finalOut
    
    def train(self,trainX,label,numEpochs=1000):
        print "Training started"
        for i in range(numEpochs):
            for idx in range(trainX.shape[0]):
                trainingRow = np.append(trainX[idx],1.0)
                thetaX = sigmoid(np.dot(trainingRow ,self.weight.transpose())) # Here h(x) is sigmoid as compared to theta*X of linear regression
                delta =  trainingRow * (thetaX - label[idx])
                self.weight = self.weight - (self.learningRate * delta)
        print "Training Ended"   

        


In [ ]:
# Softmax regression 

